### ISSUE TITLE
Module fails validation in Foundry v10

### ISSUE THREAD

**Issue by Eagle0600** [League-of-Foundry-Developers/codemirror-lib#11]
`setup.js:141 [_CodeMirror] Metadata validation failed for module "_CodeMirror": The file "addon/mode/matchbrackets.js" included by module _CodeMirror does not exist`

**Comment by yahavatar** [comment]
OK. Looks like the package that is being pulled down by doing an install in Foundry 10 does not match the one you get by downloading directly from Github. Here's my workaround:
1) Do the install from Foundry. It will fail, but it will download the files and register the module.
2) Manually download the latest _CodeMirror.zip from GitHub. Unpack into the existing one located somewhere like: "Data\modules\_CodeMirror\"
3) Restart Foundry. You should now see it in your list of modules.

Not elegant, but it works. You might just be able to edit the manifest.json and change the entry for matchbrackets.js. However, I decided not to do this because there might have been other file differences. I'm not really sure what might cause this, GitHub caching maybe...?

yah.
